<?php
/**
 * @file
 */

include_once('humanitarianresponse_core.features.inc');

function humanitarianresponse_core_feeds_check($id, $url) {
  drupal_set_time_limit(0);
  $source = feeds_source($id);
  $tmp_url = $source->config['FeedsHTTPFetcher']['source'];
  if ($tmp_url == "") {
    $source->addConfig(array('FeedsHTTPFetcher' => array('source' => $url)));
    $source->save();

    // Refresh feed if import on create is selected.
    if ($source->importer->config['import_on_create']) {
      $source->startImport();
    }

    // Add to schedule, make sure importer is scheduled, too.
    $source->schedule();
    $source->importer->schedule();
  }
}

/**
 * Rebuilds taxonomy menu without Batch API. This is needed to avoid
 * issues when taxonomy menu is rebuilt from cron
 */
function humanitarianresponse_core_taxonomy_menu_rebuild($vid) {
  // Remove all of the menu items for this vocabulary
  _taxonomy_menu_delete_all($vid);

  // Only insert the links if a menu is set
  if (variable_get(_taxonomy_menu_build_variable('vocab_menu', $vid), FALSE)) {
    $menu_name = variable_get(_taxonomy_menu_build_variable('vocab_menu', $vid), FALSE);
    // Check to see if we should had a vocab item
    if (variable_get(_taxonomy_menu_build_variable('voc_item', $vid), FALSE)) {
      $args = array(
        'vid' => $vid,
        'menu_name' => $menu_name,
      );
      taxonomy_menu_handler('insert', $args);
    }
    $terms = taxonomy_get_tree($vid);
    // Loop through $terms to process each term.
    for ($i=0; $i<count($terms); $i++) {
      $args = array(
        'term' => $terms[$i],
        'menu_name' => $menu_name,
      );
      $mlid = taxonomy_menu_handler('insert', $args);
    }
    menu_rebuild();
  }
}
